apiVersion: apps/v1
kind: Deployment
metadata:
  name: milestone-1-db
  labels:
    app: m1-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m1-db
  template:
    metadata:
      labels:
        app: m1-db
    spec:
      volumes:
      - name: pv0001-storage
        persistentVolumeClaim:
          claimName: pv0001-claim
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: mysecretpassword
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: pv0001-storage
          mountPath: /var/lib/postgresql/data/pgdata
