apiVersion: apps/v1
kind: Deployment
metadata:
  name: milestone-1
  labels:
    app: m1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: m1
  template:
    metadata:
      labels:
        app: m1
    spec:
      containers:
      - name: milestone-1
        image: robfz/m1:v0.25
        ports:
        - containerPort: 3000
